# Redes de Hopfield

## Almacenamiento de un patrón

In [200]:
import numpy as np
def signo_vec(vec):
    vec[vec >0]=1
    vec[vec <=0]=-1
    return vec

p1=np.array([[1,1,1,1,-1,-1,1,1,1,1]],dtype='float64')
p2=np.array([[1,1,-1,-1,-1,-1,1,-1,-1,1]],dtype='float64')
p3=np.array([[1,-1,1,-1,1,-1,1,-1,-1,1]],dtype='float64')
w=np.dot(p1.T,p1)
w-=np.diagonal(w)*np.eye(w.shape[0])

In [201]:
print("La matriz de pesos queda")
print(w)
print("Verifiquemos que el patrón haya sido almacenado")
print(signo_vec(np.dot(w,p1.T)).T)
print("La energía del patrón p1 es:")
print(-0.5*np.dot(p1,np.dot(w,p1.T)))
print("La energía del patrón p2 es:")
print(-0.5*np.dot(p2,np.dot(w,p2.T)))
print("La energía del patrón p3 es:")
print(-0.5*np.dot(p3,np.dot(w,p3.T)))
print("La salida del patrón p2 es:")
p2_out=signo_vec(np.dot(w,p2.T)).T
print(p2_out)
print("La energía para ese patrón es:")
print(-0.5*np.dot(p2_out,np.dot(w,p2_out.T)))
print("Verifiquemos que pasa con -p1")
print(signo_vec(np.dot(w,-p1.T)).T)
print("La energía del patrón p1 es:")
print(-0.5*np.dot(-p1,np.dot(w,-p1.T)))

La matriz de pesos queda
[[ 0.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
 [ 1.  0.  1.  1. -1. -1.  1.  1.  1.  1.]
 [ 1.  1.  0.  1. -1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1.  0. -1. -1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  0.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  1.  0. -1. -1. -1. -1.]
 [ 1.  1.  1.  1. -1. -1.  0.  1.  1.  1.]
 [ 1.  1.  1.  1. -1. -1.  1.  0.  1.  1.]
 [ 1.  1.  1.  1. -1. -1.  1.  1.  0.  1.]
 [ 1.  1.  1.  1. -1. -1.  1.  1.  1.  0.]]
Verifiquemos que el patrón haya sido almacenado
[[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]]
La energía del patrón p1 es:
[[-45.]]
La energía del patrón p2 es:
[[ 3.]]
La energía del patrón p3 es:
[[ 5.]]
La salida del patrón p2 es:
[[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]]
La energía para ese patrón es:
[[-45.]]
Verifiquemos que pasa con -p1
[[-1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]]
La energía del patrón p1 es:
[[-45.]]


## Almacenamiento de varios patrones

In [74]:
w=w+np.dot(p2.T,p2)
w-=np.diagonal(w)*np.eye(w.shape[0])

In [75]:
print("La matriz de pesos queda")
print(w)
print("Verifiquemos que el patrón haya sido almacenado")
print(signo_vec(np.dot(w,p2.T)).T)
print("La energía del patrón p1 es:")
print(-0.5*np.dot(p1,np.dot(w,p1.T)))
print("La energía del patrón p2 es:")
print(-0.5*np.dot(p2,np.dot(w,p2.T)))
print("La energía del patrón p3 es:")
print(-0.5*np.dot(p3,np.dot(w,p3.T)))
p3_out=signo_vec(np.dot(w,p3_out.T)).T
print("La salida para p3 es:")
print(p3_out)
print("Y la energía")
print(-0.5*np.dot(p3_out,np.dot(w,p3_out.T)))
print("La segunda iteración del patrón p2 es:")
p2_out=signo_vec(np.dot(w,p2.T)).T
print(p2_out)
print(-0.5*np.dot(p2_out,np.dot(w,p2_out.T)))
print("La tercera iteración del patrón p2 es:")
p2_out=signo_vec(np.dot(w,p2.T)).T
print(p2_out)
print(-0.5*np.dot(p2_out,np.dot(w,p2_out.T)))

La matriz de pesos queda
[[ 0.  2.  0.  0. -2. -2.  2.  0.  0.  2.]
 [ 2.  0.  0.  0. -2. -2.  2.  0.  0.  2.]
 [ 0.  0.  0.  2.  0.  0.  0.  2.  2.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  2.  2.  0.]
 [-2. -2.  0.  0.  0.  2. -2.  0.  0. -2.]
 [-2. -2.  0.  0.  2.  0. -2.  0.  0. -2.]
 [ 2.  2.  0.  0. -2. -2.  0.  0.  0.  2.]
 [ 0.  0.  2.  2.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  2.  2.  0.  0.  0.  2.  0.  0.]
 [ 2.  2.  0.  0. -2. -2.  2.  0.  0.  0.]]
Verifiquemos que el patrón haya sido almacenado
[[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]]
La energía del patrón p1 es:
[[-42.]]
La energía del patrón p2 es:
[[-42.]]
La energía del patrón p3 es:
[[ 2.]]
La salida para p3 es:
[[-1. -1.  1.  1.  1.  1. -1.  1.  1. -1.]]
Y la energía
[[-42.]]
La segunda iteración del patrón p2 es:
[[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]]
[[-42.]]
La tercera iteración del patrón p2 es:
[[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]]
[[-42.]]


In [76]:
w=w+np.dot(p3.T,p3)
w-=np.diagonal(w)*np.eye(w.shape[0])

In [77]:
print("La matriz de pesos queda")
print(w)
print("Verifiquemos que el patrón haya sido almacenado")
print(signo_vec(np.dot(w,p2.T)).T)
print("La energía del patrón p1 es:")
print(-0.5*np.dot(p1,np.dot(w,p1.T)))
print("La energía del patrón p2 es:")
print(-0.5*np.dot(p2,np.dot(w,p2.T)))
print("La energía del patrón p3 es:")
print(-0.5*np.dot(p3,np.dot(w,p3.T)))

La matriz de pesos queda
[[ 0.  1.  1. -1. -1. -3.  3. -1. -1.  3.]
 [ 1.  0. -1.  1. -3. -1.  1.  1.  1.  1.]
 [ 1. -1.  0.  1.  1. -1.  1.  1.  1.  1.]
 [-1.  1.  1.  0. -1.  1. -1.  3.  3. -1.]
 [-1. -3.  1. -1.  0.  1. -1. -1. -1. -1.]
 [-3. -1. -1.  1.  1.  0. -3.  1.  1. -3.]
 [ 3.  1.  1. -1. -1. -3.  0. -1. -1.  3.]
 [-1.  1.  1.  3. -1.  1. -1.  0.  3. -1.]
 [-1.  1.  1.  3. -1.  1. -1.  3.  0. -1.]
 [ 3.  1.  1. -1. -1. -3.  3. -1. -1.  0.]]
Verifiquemos que el patrón haya sido almacenado
[[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]]
La energía del patrón p1 es:
[[-37.]]
La energía del patrón p2 es:
[[-45.]]
La energía del patrón p3 es:
[[-43.]]


In [164]:
# Construiremos un nuevo patrón tal que p4=p1+p2+p3

p4=signo_vec(p1+p2+p3)
w=w+np.dot(p4.T,p4)
w-=np.diagonal(w)*np.eye(w.shape[0])

In [166]:
print("La matriz de pesos queda")
print(w)
print("Verifiquemos que el patrón haya sido almacenado")
print(signo_vec(np.dot(w,p2.T)).T)
print("La energía del patrón p1 es:")
print(-0.5*np.dot(p1,np.dot(w,p1.T)))
print("La energía del patrón p2 es:")
print(-0.5*np.dot(p2,np.dot(w,p2.T)))
print("La energía del patrón p3 es:")
print(-0.5*np.dot(p3,np.dot(w,p3.T)))
print("La energía del patrón p4 es:")
print(-0.5*np.dot(p4,np.dot(w,p4.T)))
print("La energía de un patrón vecino a p4 es:")
p4[0,5]=p4[0,5]*(-1)
print(-0.5*np.dot(p4,np.dot(w,p4.T)))


La matriz de pesos queda
[[ 0.  3.  3. -3. -3. -5.  5. -3. -3.  5.]
 [ 3.  0.  1. -1. -5. -3.  3. -1. -1.  3.]
 [ 3.  1.  0. -1. -1. -3.  3. -1. -1.  3.]
 [-3. -1. -1.  0.  1.  3. -3.  5.  5. -3.]
 [-3. -5. -1.  1.  0.  3. -3.  1.  1. -3.]
 [-5. -3. -3.  3.  3.  0. -5.  3.  3. -5.]
 [ 5.  3.  3. -3. -3. -5.  0. -3. -3.  5.]
 [-3. -1. -1.  5.  1.  3. -3.  0.  5. -3.]
 [-3. -1. -1.  5.  1.  3. -3.  5.  0. -3.]
 [ 5.  3.  3. -3. -3. -5.  5. -3. -3.  0.]]
Verifiquemos que el patrón haya sido almacenado
[[ 1.  1.  1. -1. -1. -1.  1. -1. -1.  1.]]
La energía del patrón p1 es:
[[-43.]]
La energía del patrón p2 es:
[[-99.]]
La energía del patrón p3 es:
[[-69.]]
La energía del patrón p4 es:
[[-67.]]
La energía de un patrón vecino a p4 es:
[[-133.]]


# Problemas del almacenamiento sincrónico: oscilaciones bi-fase

<img src="./oscilaciones.png" alt="oscilacion">

si actualizo en forma sincrónica:

(0,0) -> (1,1) -> (0,0) -> (1,1) ->...

si actualizo en forma asincrónica:

(0,0) -> (1,0) -> (1,0) -> (1,0) -> ...

In [190]:
import numpy as np
import random as rand
def normalize(res):
    if res >0:
        res=1
    else:
        res=-1
    return res

def normalize_stoc(res,T):
    p=1/(1+np.exp(-2*res/float(T)))
    val=rand.uniform(0, 1)
    if val<p:
        res=1
    else:
        res=-1
    return res
class hopfield:
    def __init__(self,N_neurons=0,enableStochastic=False, train_method='default'):
        self.model(N_neurons,enableStochastic=False, train_method='default')
    def model(self, N_neurons,enableStochastic=False, train_method='default'):
        self.weights=np.zeros([N_neurons,N_neurons])
        self.N_neurons=N_neurons
        self.enableStochastic=enableStochastic
        self.train_method=train_method
    def train(self, X, method='default'):
        self.method=method
        # X: rows patterns, cols elements of pattern
        self.weights=np.dot(np.array(X,dtype='float64').T,np.array(X,dtype='float64'))
        self.weights-=np.diagonal(self.weights)*np.eye(self.weights.shape[0])
    def addTrain(self,X):
        if(self.method=='default'):
            self.weights+=np.dot(np.array(X,dtype='float64').T,np.array(X,dtype='float64'))
            self.weights-=np.diagonal(self.weights)*np.eye(self.weights.shape[0])
    def predict_cold(self,x,iters):
        res=np.array(x,dtype='float64')
        for i in range(1,iters):
            idx=np.random.choice(res.size)
            res[idx]=normalize(np.dot(self.weights[idx],res))
            print(res)
            energy=self.energy(res)
            print(energy)
        return res,energy
    def predict_hot(self,x,iters, T):
        res=np.array(x,dtype='float64')
        x=x.flatten()
        for i in range(1,iters):
            idx=np.random.choice(res.size)
            res[idx]=normalize_stoc(np.dot(self.weights[idx],res),T)
            print(res)
            energy=self.energy(res)
            print(energy)
        return res,energy
    def energy(self,x):
        return -0.5*np.dot(np.dot(x,self.weights),x)

In [191]:
hop=hopfield()
hop.model(10)

In [192]:
hop.weights

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [193]:
hop.train(np.vstack([p1,p2]))
hop.weights

array([[ 0.,  2.,  0.,  0., -2., -2.,  2.,  0.,  0.,  2.],
       [ 2.,  0.,  0.,  0., -2., -2.,  2.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  2.,  0.,  0.,  0.,  2.,  2.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  0.,  0.,  2.,  2.,  0.],
       [-2., -2.,  0.,  0.,  0.,  2., -2.,  0.,  0., -2.],
       [-2., -2.,  0.,  0.,  2.,  0., -2.,  0.,  0., -2.],
       [ 2.,  2.,  0.,  0., -2., -2.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  2.,  2.,  0.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  2.,  2.,  0.,  0.,  0.,  2.,  0.,  0.],
       [ 2.,  2.,  0.,  0., -2., -2.,  2.,  0.,  0.,  0.]])

In [194]:
print(p4)
res,energy=hop.predict_hot(p4.flatten(),10,1)

[[ 1.  1.  1. -1. -1. -1.  1. -1. -1.  1.]]
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0
[ 1.  1. -1. -1. -1. -1.  1. -1. -1.  1.]
-42.0


In [196]:
res,energy=hop.predict_hot(np.array([1,1,1,1,1,1,1,1,1,1]),100,10)

[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[-1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-10.0
[-1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-10.0
[-1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
-22.0
[-1.  1.  1. -1. -1. -1.  1.  1.  1.  1.]
-10.0
[-1.  1.  1. -1. -1. -1. -1.  1.  1.  1.]
2.0
[-1.  1.  1. -1. -1. -1. -1.  1.  1.  1.]
2.0
[-1.  1.  1. -1.  1. -1. -1.  1.  1.  1.]
6.0
[-1.  1.  1. -1.  1. -1. -1.  1.  1.  1.]
6.0
[-1.  1.  1. -1.  1. -1.  1.  1.  1.  1.]
2.0
[-1.  1.  1. -1. -1. -1.  1.  1.  1.  1.]
-10.0
[-

In [141]:
res,energy=hop.predict_hot([1,1,1,1,1,1,1,1,1,1],100,0)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
-10.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
-22.0
[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
-42.0
[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
-42.0
[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
-42.0
[ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.

/home/cselmo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()


In [94]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)
clf.cv_results_.keys()
clf.cv_results_

{'mean_fit_time': array([ 0.00040054,  0.00055432,  0.00044203,  0.00062601]),
 'mean_score_time': array([ 0.00025137,  0.00027108,  0.00025566,  0.00025463]),
 'mean_test_score': array([ 0.98      ,  0.97333333,  0.97333333,  0.98      ]),
 'mean_train_score': array([ 0.98999802,  0.98336304,  0.97999604,  0.97999604]),
 'param_C': masked_array(data = [1 1 10 10],
              mask = [False False False False],
        fill_value = ?),
 'param_kernel': masked_array(data = ['linear' 'rbf' 'linear' 'rbf'],
              mask = [False False False False],
        fill_value = ?),
 'params': ({'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'}),
 'rank_test_score': array([1, 3, 3, 1], dtype=int32),
 'split0_test_score': array([ 1.        ,  0.98039216,  1.        ,  0.98039216]),
 'split0_train_score': array([ 0.97979798,  0.96969697,  0.95959596,  0.95959596]),
 'split1_test_score': array([ 0.96078431,  0.96078431,  0.92